repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: trailing-whitespace
        exclude: notebooks/.*\.py
      - id: check-ast
      - id: check-added-large-files
        exclude: notebooks/.*\.ipynb
      - id: check-toml
      - id: check-json
      - id: check-yaml

  - repo: https://github.com/psf/black
    rev: 23.11.0
    hooks:
      - id: black
        exclude: (docs/|notebooks/)

  - repo: https://github.com/mwouts/jupytext
    rev: v1.15.2
    hooks:
      - id: jupytext
        args: ["--from", ".ipynb", "--to", "py:percent", "--pipe-fmt", "black"]
        files: "\\.ipynb$"
        additional_dependencies:
          - black==23.11.0

  - repo: https://github.com/hadialqattan/pycln
    rev: v2.3.0
    hooks:
      - id: pycln
        args: ["-a"]
        exclude: (config/|data/|docs/|docker/|models/|notebooks/|references/)

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.6.1
    hooks:
      - id: mypy
        args: []
        additional_dependencies: []
        exclude: (/test_|/tests/|docs/|notebooks/.*\.py)

  - repo: https://github.com/timothycrosley/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--profile", "black"]
        exclude: (docs/|notebooks/)

  - repo: https://github.com/PyCQA/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        name: flake8
        entry: flake8
        language: python
        types: [python]
        args: [--config, .flake8]
        exclude: (docs/|notebooks/.*\.py)

  - repo: https://github.com/pycqa/pylint
    rev: v3.0.2
    hooks:
      - id: pylint
        exclude: (/test_|tests/|docs/|notebooks/.*\.py)

  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.5
    hooks:
      - id: bandit
        args: [-c, pyproject.toml, --recursive, src]
        additional_dependencies: [".[toml]"]
        exclude:  (notebooks/)
